### PR TITLE
Added field to track description

### PR DESCRIPTION
**Pull request by jasonyoumans**
Added description field to avoid the need to remember which header values map to specific use cases.

### CODE REVIEW

**Comment by 67726e** [comment]
Looks good. I'll pull down, test, and get a release out to Google today.

**Comment by 67726e** [comment]
Ironically enough, I was just wondering last night whether y'all still used this plugin or not, and just noticed the PR this morning. Anyhow, thanks for the addition Jason!

**Comment by jasonyoumans** [comment]
I use it so much that I finally needed the descriptions to keep track of the entries.  BTW, I wasn't sure whether the 2.2 upgrade code could have replaced the 2.1 function.  I was unable to test it b/c I think the process is tied to it being in the store.  Probably a lack of my knowledge here, but wanted to throw that out in case it warrants any mods prior to submission to the store.

**Comment by 67726e** [comment]
@jasonyoumans Got a little sand-bagged today so I haven't had time to thoroughly poke everything, but by all outward appearances it works fine and all. The upgrade code in particular, I'll need to update. It's basically supposed to walk in sequential order (think MyBatis migrations) to update the data into the latest-and-greatest form. That said, my last commit to the project was almost a year ago, so I may need to freshen my memory to be certain. Either way, should have this out into the wild later tomorrow so long as I don't get hit by any buses.

As for testing, if you're in Chrome and click on the settings tab in the top-right (the hamburger button) and go to Settings -> Extensions (top-left tab) you'll see a checkbox up at the top for `Developer Mode`. Check that, and then click the `Load Unpacked Extensions` button that appears and point it to root of the Header-Editor project directory. Should load up the extension from there, and you would have two extensions in your Chrome if you have the version from the web store.

**Comment by 67726e** [comment]
@jasonyoumans  I also might move the description field to the far-right as to be out of the way for the common use-case. Just nit-picking at this point. Given that I haven't really used this plugin much since leaving BL, let me know if there are any other features that might make the plugin easier/convenient for you. I'm apparently up to about 2.4K weekly uses for the plugin, and don't get much feedback.

**Comment by 67726e** [comment]
@jasonyoumans I published the new release this morning. It should be released by Google in the next hour or so.

**Comment by jasonyoumans** [comment]
Sorry for delay and thanks for pushing it up.  Good suggestion.  I will move the field and do another PR tonight.

**Pull request merged**
